# Using Pandas

In [109]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [110]:
data = pd.read_csv("data/vehicles.csv")

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [111]:
## 35952 rows Ã— 15 columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

In [112]:
data.loc[data["Make"].str.contains("Dutton", case=False), "Make"] = "Dutton"


data["CO2 Emission Grams/Mile"] = data["CO2 Emission Grams/Mile"] / 1.6
data.rename(columns={"CO2 Emission Grams/Mile": "CO2 Emission Grams/Km"})

data["Transmission_updated"] = data["Transmission"].copy()
data.loc[data["Transmission_updated"].str.startswith("Auto"), "Transmission_updated"] = "Automatic"
data.loc[data["Transmission_updated"].str.startswith("Manual"), "Transmission_updated"] = "Manual"

data[["City MPG", "Highway MPG", "Combined MPG"]] = data[["City MPG", "Highway MPG", "Combined MPG"]] * 0.425
data.rename(columns={"City MPG": "City km_per_liter","Highway MPG" : "Highway km_per_liter","Combined MPG" : "Combined km_per_liter"})

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,326.727941,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,427.259615,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,347.148438,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,427.259615,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,347.148438,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,152.500000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.875000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,152.500000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,153.750000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,159.375000,1150

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City km_per_liter,Highway km_per_liter,Combined km_per_liter,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission_updated
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,7.650,7.225,7.225,326.727941,1950,Automatic
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.525,5.525,5.525,427.259615,2550,Automatic
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,6.800,7.225,6.800,347.148438,2100,Automatic
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,5.525,5.525,5.525,427.259615,2550,Automatic
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,5.950,8.925,6.800,347.148438,2550,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.450,16.150,15.300,152.500000,1100,Automatic
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.450,16.150,15.300,151.875000,1100,Automatic
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.450,16.150,15.300,152.500000,1100,Automatic
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,14.450,16.575,15.300,153.750000,1100,Automatic
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,13.600,16.575,14.875,159.375000,1150,Manual

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [117]:
data.Make.value_counts()

Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1677
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Lotus                                 53
Roush Performance                     53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Bugatti                                8
Yugo                                   8
Genesis                                7
Tecstar, LP                            6
Mcevoy Motors                          6
Bertone                                5
VPG                                    5
Saleen                                 5
Panther Car Company Limited            4
Saleen Performance                     4
AM General                             4
Grumman Olson                          4
Texas Coach Company                    4
Vector                                 4
Autokraft Limited                      4
TVR Engineering Ltd                    4
Bitter Gmbh and Co. Kg                 3
Evans Automobiles                      3
BMW Alpina                             3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Dutton                                 3
Morgan                                 3
Ruf Automobile Gmbh                    2
Bill Dovell Motor Car Company          2
Mobility Ventures LLC                  2
Laforza Automobile Inc                 2
CCC Engineering                        2
PAS Inc - GMC                          2
PAS, Inc                               2
SRT                                    2
Pagani                                 2
Red Shift Ltd.                         2
Pininfarina                            2
Quantum Technologies                   2
Isis Imports Ltd                       1
Mahindra                               1
ASC Incorporated                       1
Aurora Cars Ltd                        1
Volga Associated Automobile            1
Vixen Motor Company                    1
JBA Motorcars, Inc.                    1
London Coach Co Inc                    1
London Taxi                            1
Import Foreign Auto Sales Inc          1
Environmental Rsch and Devp Corp       1
Grumman Allied Industries              1
Goldacre                               1
General Motors                         1
Shelby                                 1
Fisker                                 1
Panos                                  1
Panoz Auto-Development                 1
Excalibur Autos                        1
Qvale                                  1
Lambda Control Systems                 1
Name: Make, dtype: int64

In [119]:
## Number of car makers
data["Make"].nunique()

125

In [120]:
## Number of models
data["Model"].nunique()

3608

In [123]:
## Years
print(data["Year"].min())
print(data["Year"].max())

1984
2017

In [125]:
## Engines
print(data["Engine Displacement"].min())
print(data["Engine Displacement"].max())

0.6
8.4

In [126]:
data["Fuel Type"].value_counts()

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

In [130]:
print(data.iloc[data["Fuel Barrels/Year"].argmax()])
print(data.iloc[data["Fuel Barrels/Year"].argmin()])

Make                            Lamborghini
Model                              Countach
Year                                   1986
Engine Displacement                     5.2
Cylinders                              12.0
Transmission                   Manual 5-spd
Drivetrain                 Rear-Wheel Drive
Vehicle Class                   Two Seaters
Fuel Type                           Premium
Fuel Barrels/Year                 47.087143
City MPG                               2.55
Highway MPG                            4.25
Combined MPG                          2.975
CO2 Emission Grams/Mile          793.482143
Fuel Cost/Year                         5800
Transmission_updated                 Manual
Name: 20894, dtype: object
Make                                   Honda
Model                      Civic Natural Gas
Year                                    2012
Engine Displacement                      1.8
Cylinders                                4.0
Transmission                 Automatic 5-spd
Drivetrain                 Front-Wheel Drive
Vehicle Class                   Compact Cars
Fuel Type                                CNG
Fuel Barrels/Year                       0.06
City MPG                              11.475
Highway MPG                            16.15
Combined MPG                          13.175
CO2 Emission Grams/Mile           142.933972
Fuel Cost/Year                          1000
Transmission_updated               Automatic
Name: 17395, dtype: object

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [144]:
rr = data.groupby("Make")["CO2 Emission Grams/Mile"].mean()
rr.sort_values()
## Vector has the worse CO" Emissions on average

Make
Fisker                              105.625000
smart                               154.394097
Fiat                                190.416600
Daihatsu                            193.867538
MINI                                196.073039
Scion                               207.122449
Geo                                 210.673494
Yugo                                222.542660
Grumman Olson                       222.710889
Honda                               223.457861
Renault                             224.891560
Saturn                              235.197046
Hyundai                             240.638558
Red Shift Ltd.                      241.494565
Dacia                               241.494565
Daewoo                              242.348435
Kia                                 244.149253
Volkswagen                          245.463576
Suzuki                              245.467211
Panoz Auto-Development              252.471591
Bertone                             252.471591
Subaru                              252.697538
Eagle                               256.967516
Pontiac                             259.016999
Plymouth                            260.530236
Mazda                               263.326589
Acura                               264.115828
Consulier Industries Inc            264.494048
Quantum Technologies                264.494048
Qvale                               264.494048
Mitsubishi                          269.670067
Buick                               271.539908
Toyota                              272.372377
Volvo                               272.377347
Pininfarina                         272.403559
Mercury                             273.074295
Panther Car Company Limited         274.412574
Oldsmobile                          275.447765
Lexus                               276.846835
Saab                                277.180179
Isis Imports Ltd                    277.718750
Lotus                               277.807869
Chrysler                            279.230307
Audi                                281.722401
Mcevoy Motors                       282.591009
Nissan                              285.098370
BMW                                 285.921467
Infiniti                            288.657709
London Taxi                         289.204545
Porsche                             289.881598
Alfa Romeo                          289.970072
Genesis                             290.089286
Import Foreign Auto Sales Inc       292.335526
Evans Automobiles                   292.335526
Volga Associated Automobile         292.335526
Peugeot                             293.267053
Ram                                 300.102522
Lincoln                             304.339267
McLaren Automotive                  305.755876
Sterling                            306.028803
Isuzu                               307.010865
Merkur                              307.170667
Jaguar                              308.371789
TVR Engineering Ltd                 308.576389
Goldacre                            308.576389
General Motors                      308.576389
Cadillac                            310.175694
Jeep                                311.737925
Mercedes-Benz                       313.239468
American Motors Corporation         316.099264
Mahindra                            318.125000
Chevrolet                           320.424563
Ford                                322.166321
Morgan                              326.727941
Bill Dovell Motor Car Company       326.727941
Grumman Allied Industries           326.727941
Shelby                              326.727941
Lambda Control Systems              326.727941
Autokraft Limited                   336.938189
Dabryan Coach Builders Inc          341.249183
Mobility Ventures LLC               342.187500
CX Automotive                       345.316862
Dodge                               346.565515
ASC Incorporated                    347.148438
London Coach Co Inc                 347.148438
Environmental Rsch and Devp Corp    347.148438
BMW Alpina                          354.862847
Bitter Gmbh and Co. Kg              354.862847
VPG                                 357.078686
GMC                                 357.181983
Import Trade Services               358.293690
Federal Coach                       362.693019
Spyker                              363.589555
Hummer                              367.507519
CCC Engineering                     370.291667
Panos                               370.291667
PAS Inc - GMC                       370.291667
Aurora Cars Ltd                     370.291667
JBA Motorcars, Inc.                 370.291667
Saleen                              373.089200
Land Rover                          375.459419
SRT                                 379.375000
AM General                          382.098902
Maserati                            387.937669
Roush Performance                   388.696957
J.K. Motors                         393.277248
PAS, Inc                            396.741071
Excalibur Autos                     396.741071
Vixen Motor Company                 397.656250
Wallace Environmental               411.243768
Saleen Performance                  412.000343
Pagani                              419.375000
Aston Martin                        420.386110
Ruf Automobile Gmbh                 427.259615
Tecstar, LP                         427.259615
Bentley                             428.779164
Ferrari                             445.397718
Maybach                             455.973299
Texas Coach Company                 462.864583
Lamborghini                         471.739061
Rolls-Royce                         478.172906
Dutton                              479.200980
Laforza Automobile Inc              504.943182
Bugatti                             545.664062
Vector                              655.724826
Name: CO2 Emission Grams/Mile, dtype: float64

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [145]:
data.groupby("Transmission_updated")["Fuel Barrels/Year"].mean()

Transmission_updated
Automatic    18.043152
Manual       16.704904
Name: Fuel Barrels/Year, dtype: float64